import icons from "@/constants/icons";

const url =
  process.env.NODE_ENV === "development" ? "https://kapeed07.github.io" : "";

const projects = [
  {
    _id: 1,
    logo: "coheto",
    title: "CoHeTo",
    desc:
      "CoHeTo helps you go in presentation mode on Codepen and provides you some extra space to work with",
    color: "green",
    url: `${url}/coheto`,
    shade: "500",
    icon: icons.TOGGLE,
    status: true,
  },
  {
    _id: 2,
    logo: "",
    title: "Contact App",
    desc: "contact list with search functionality",
    color: "blue",
    url: `${url}/contact-app`,
    shade: 500,
    icon: icons.BADGE,
    status: true,
  },
  {
    _id: 3,
    logo: "",
    title: "Giflib",
    desc:
      "CoHeTo helps you go in presentation mode on Codepen and provides you some extra space to work with.",
    color: "pink",
    url: `${url}`,
    shade: 500,
    icon: icons.IMAGES,
    status: false,
  },
  {
    _id: 4,
    logo: "",
    title: "Timer",
    desc: "Digital timer for 10 seconds",
    color: "indigo",
    url: `https://codepen.io/kapeed07/pen/VJvOeW`,
    shade: 500,
    icon: icons.STOPWATCH,
    status: true,
  },
  {
    _id: 5,
    logo: "",
    title: "FlexBox Visualiser",
    desc: "Playground for flexbox",
    color: "red",
    url: `${url}/flexbox`,
    shade: 500,
    icon: icons.BUROMOBEL,
    status: true,
  },
  {
    _id: 6,
    logo: "",
    title: "Score keeper game",
    desc: "Score keeper game",
    color: "orange",
    url: "https://codepen.io/kapeed07/details/jwbNjZ",
    shade: 500,
    icon: icons.DICE,
    status: true,
  },
  {
    _id: 7,
    logo: "",
    title: "Color guessing game",
    desc: "Color guessing game",
    color: "teal",
    url: "https://codepen.io/kapeed07/pen/QgbWoX",
    shade: 500,
    icon: icons.PALETTE,
    status: true,
  },
  {
    _id: 8,
    logo: "",
    title: "Counter App",
    desc:
      "CoHeTo helps you go in presentation mode on Codepen and provides you some extra space to work with.",
    color: "orange",
    url: `${url}`,
    shade: 500,
    icon: icons.STOPWATCH,
    status: false,
  },
  {
    _id: 9,
    logo: "",
    title: "Checkbox app | Subscription tracker",
    desc:
      "CoHeTo helps you go in presentation mode on Codepen and provides you some extra space to work with.",
    color: "blue",
    url: `${url}`,
    shade: 500,
    icon: icons.DOUBLECHECK,
    status: false,
  },
  {
    _id: 10,
    logo: "",
    title: "81Hut",
    desc:
      "CoHeTo helps you go in presentation mode on Codepen and provides you some extra space to work with.",
    color: "pink",
    url: `${url}`,
    shade: 500,
    icon: icons.HOME,
    status: false,
  },
  {
    _id: 11,
    logo: "",
    title: "Todo | using trello api",
    desc:
      "CoHeTo helps you go in presentation mode on Codepen and provides you some extra space to work with.",
    color: "red",
    url: `${url}`,
    shade: 500,
    icon: icons.LIST,
    status: false,
  },
  {
    _id: 12,
    logo: "",
    title: "Git client | Electron",
    desc:
      "CoHeTo helps you go in presentation mode on Codepen and provides you some extra space to work with.",
    color: "green",
    url: `${url}`,
    shade: 500,
    icon: icons.CODEBRANCH,
    status: false,
  },
  {
    _id: 13,
    logo: "",
    title: "vidly app",
    desc:
      "CoHeTo helps you go in presentation mode on Codepen and provides you some extra space to work with.",
    color: "pink",
    url: `${url}`,
    shade: 500,
    icon: icons.FILM,
    status: false,
  },
  {
    _id: 14,
    logo: "",
    title: "leave application chrome extension",
    desc:
      "CoHeTo helps you go in presentation mode on Codepen and provides you some extra space to work with.",
    color: "yellow",
    url: `${url}`,
    shade: 500,
    icon: icons.TRAILER,
    status: false,
  },
  {
    _id: 15,
    logo: "",
    title: "DP Visualiser",
    desc:
      "CoHeTo helps you go in presentation mode on Codepen and provides you some extra space to work with.",
    color: "purple",
    url: `${url}`,
    shade: 500,
    icon: icons.SITEMAP,
    status: false,
  },
];

export default projects;
